// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameUserActivity = "c_user_activity"

// UserActivity mapped from table <c_user_activity>
type UserActivity struct {
	ID            int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`      // 自增ID
	UserID        int64                 `gorm:"column:user_id;not null" json:"user_id"`                 // 用户ID
	LatestLoginAt int64                 `gorm:"column:latest_login_at;not null" json:"latest_login_at"` // 最近登陆
	CreateTime    int64                 `gorm:"column:create_time;autoCreateTime" json:"create_time"`   // 创建时间
	UpdateTime    int64                 `gorm:"column:update_time;autoUpdateTime" json:"update_time"`   // 更新时间
	ModifyTime    time.Time             `gorm:"column:modify_time;autoUpdateTime" json:"modify_time"`   // 维护字段-更新时间
	DeleteTime    soft_delete.DeletedAt `gorm:"column:delete_time;not null" json:"delete_time"`         // 删除时间
}

// TableName UserActivity's table name
func (*UserActivity) TableName() string {
	return TableNameUserActivity
}

// IsEmpty 判断空
func (m *UserActivity) IsEmpty() bool {
	if m == nil {
		return true
	}

	return m.ID == 0
}
