// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameSysDict = "sys_dict"

// SysDict mapped from table <sys_dict>
type SysDict struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`    // 自增ID
	DataType   string                `gorm:"column:data_type" json:"data_type"`                    // 数字类型
	ItemKey    string                `gorm:"column:item_key" json:"item_key"`                      // 键
	ItemValue  string                `gorm:"column:item_value" json:"item_value"`                  // 值
	Xh         int32                 `gorm:"column:xh" json:"xh"`                                  // 排序序号
	OutData    string                `gorm:"column:out_data" json:"out_data"`                      // 外部数据
	PID        int64                 `gorm:"column:p_id;not null" json:"p_id"`                     // 父ID
	DictDesc   string                `gorm:"column:dict_desc" json:"dict_desc"`                    // 字典描述
	DictLevel  string                `gorm:"column:dict_level" json:"dict_level"`                  // 为空时则是全局字典 否则为某个学校的全局 字典权限
	CreateTime int64                 `gorm:"column:create_time;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;autoUpdateTime" json:"update_time"` // 更新时间
	ModifyTime time.Time             `gorm:"column:modify_time;autoUpdateTime" json:"modify_time"` // 维护字段-更新时间
	DeleteTime soft_delete.DeletedAt `gorm:"column:delete_time;not null" json:"delete_time"`       // 删除时间
}

// TableName SysDict's table name
func (*SysDict) TableName() string {
	return TableNameSysDict
}

// IsEmpty 判断空
func (m *SysDict) IsEmpty() bool {
	if m == nil {
		return true
	}

	return m.ID == 0
}
