// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameSysRole = "sys_role"

// SysRole mapped from table <sys_role>
type SysRole struct {
	ID           int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`    // 角色权限ID
	RoleName     string                `gorm:"column:role_name" json:"role_name"`                    // 角色权限名称
	ParentRoleID int64                 `gorm:"column:parent_role_id;not null" json:"parent_role_id"` // 父角色权限ID
	RoleFlag     string                `gorm:"column:role_flag" json:"role_flag"`                    // 角色标记
	RoleLevel    string                `gorm:"column:role_level" json:"role_level"`                  // 角色级别
	RoleCode     string                `gorm:"column:role_code" json:"role_code"`                    // 权限编码
	CreateTime   int64                 `gorm:"column:create_time;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime   int64                 `gorm:"column:update_time;autoUpdateTime" json:"update_time"` // 更新时间
	ModifyTime   time.Time             `gorm:"column:modify_time;autoUpdateTime" json:"modify_time"` // 维护字段-更新时间
	DeleteTime   soft_delete.DeletedAt `gorm:"column:delete_time;not null" json:"delete_time"`       // 删除时间
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}

// IsEmpty 判断空
func (m *SysRole) IsEmpty() bool {
	if m == nil {
		return true
	}

	return m.ID == 0
}
