// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameSysMenu = "sys_menu"

// SysMenu mapped from table <sys_menu>
type SysMenu struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`    // 自增ID
	MenuName   string                `gorm:"column:menu_name" json:"menu_name"`                    // 资源名称
	MenuType   string                `gorm:"column:menu_type" json:"menu_type"`                    // 资源类型 0：菜单  1：按钮 2：其他
	PMenuID    int64                 `gorm:"column:p_menu_id;not null" json:"p_menu_id"`           // 父资源ID
	MenuIcon   string                `gorm:"column:menu_icon" json:"menu_icon"`                    // 资源icon
	Xh         int32                 `gorm:"column:xh" json:"xh"`                                  // 排序值
	AuthCode   string                `gorm:"column:auth_code" json:"auth_code"`                    // 位权限编码
	Remark     string                `gorm:"column:remark" json:"remark"`                          // 描述
	Path       string                `gorm:"column:path" json:"path"`                              // 过滤URI
	Redirect   string                `gorm:"column:redirect" json:"redirect"`                      // 重定向URL
	CreateTime int64                 `gorm:"column:create_time;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;autoUpdateTime" json:"update_time"` // 更新时间
	ModifyTime time.Time             `gorm:"column:modify_time;autoUpdateTime" json:"modify_time"` // 维护字段-更新时间
	DeleteTime soft_delete.DeletedAt `gorm:"column:delete_time;not null" json:"delete_time"`       // 删除时间
	IfLeaf     string                `gorm:"column:if_leaf" json:"if_leaf"`                        // 是否是叶子节点
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}

// IsEmpty 判断空
func (m *SysMenu) IsEmpty() bool {
	if m == nil {
		return true
	}

	return m.ID == 0
}
