// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameSysOrg = "sys_org"

// SysOrg mapped from table <sys_org>
type SysOrg struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`    // 自增ID
	OrgName    string                `gorm:"column:org_name" json:"org_name"`                      // 组织名称
	POrgID     int64                 `gorm:"column:p_org_id;not null" json:"p_org_id"`             // 父节点ID
	OrgFlag    string                `gorm:"column:org_flag" json:"org_flag"`                      // 组织标记
	CreateTime int64                 `gorm:"column:create_time;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;autoUpdateTime" json:"update_time"` // 更新时间
	ModifyTime time.Time             `gorm:"column:modify_time;autoUpdateTime" json:"modify_time"` // 维护字段-更新时间
	DeleteTime soft_delete.DeletedAt `gorm:"column:delete_time;not null" json:"delete_time"`       // 删除时间
}

// TableName SysOrg's table name
func (*SysOrg) TableName() string {
	return TableNameSysOrg
}

// IsEmpty 判断空
func (m *SysOrg) IsEmpty() bool {
	if m == nil {
		return true
	}

	return m.ID == 0
}
