// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`    // 自增ID
	Username   string                `gorm:"column:username;not null" json:"username"`             // 用户名
	CreateTime int64                 `gorm:"column:create_time;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;autoUpdateTime" json:"update_time"` // 更新时间
	ModifyTime time.Time             `gorm:"column:modify_time;autoUpdateTime" json:"modify_time"` // 维护字段-更新时间
	DeleteTime soft_delete.DeletedAt `gorm:"column:delete_time;not null" json:"delete_time"`       // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}

// IsEmpty 判断空
func (m *User) IsEmpty() bool {
	if m == nil {
		return true
	}

	return m.ID == 0
}
