// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"miya/user/internal/logic"
	"miya/user/internal/svc"
	"miya/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Ping(ctx context.Context, in *user.Request) (*user.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *user.GetUserReq) (*user.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) RegisterReq(ctx context.Context, in *user.GetUserReq) (*user.GetUserResp, error) {
	l := logic.NewRegisterReqLogic(ctx, s.svcCtx)
	return l.RegisterReq(in)
}
