// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"miya/api/internal/app"
	"miya/api/internal/rpc"
)

// Injectors from wire.go:

// CreateApp init application.
func CreateApp() (*app.Application, func(), error) {
	rpcService := rpc.NewServiceContext()
	application, err := app.NewApp(rpcService)
	if err != nil {
		return nil, nil, err
	}
	return application, func() {
	}, nil
}
