// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameSysRoleMenu = "sys_role_menu"

// SysRoleMenu mapped from table <sys_role_menu>
type SysRoleMenu struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`    // 自增ID
	RoleID     int64                 `gorm:"column:role_id;not null" json:"role_id"`               // 角色权限ID
	MenuID     int64                 `gorm:"column:menu_id;not null" json:"menu_id"`               // 资源ID
	CreateTime int64                 `gorm:"column:create_time;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;autoUpdateTime" json:"update_time"` // 更新时间
	ModifyTime time.Time             `gorm:"column:modify_time;autoUpdateTime" json:"modify_time"` // 维护字段-更新时间
	DeleteTime soft_delete.DeletedAt `gorm:"column:delete_time;not null" json:"delete_time"`       // 删除时间
	Type       string                `gorm:"column:type;default:0" json:"type"`                    // 角色菜单关系类型(0:该角色拥有此菜单或按钮,1:该角色拥有此菜单的子菜单或权限)
}

// TableName SysRoleMenu's table name
func (*SysRoleMenu) TableName() string {
	return TableNameSysRoleMenu
}

// IsEmpty 判断空
func (m *SysRoleMenu) IsEmpty() bool {
	if m == nil {
		return true
	}

	return m.ID == 0
}
